### PR TITLE
Update check-node-modules.sh to mention running on linux

### PR DESCRIPTION
**Pull request by robertbrignull**
What do people think of this? Is this enough of a warning to help us remember how to do things?

I'm also not actually sure if linux is strictly needed as windows might work too. All I know currently is that mac doesn't work.

### CODE REVIEW

**Review by shati-patel — APPROVED** [review]
LGTM

**Comment by aeisenberg** [comment]
Mac works fine when running this command on the codeql-action. Is there something different about this action?

**Comment by robertbrignull** [comment]
I'm not sure. Definitely a lot of inspiration for the structure of this repo was taken from the codeql-action. Could the codeql-action have advanced since then and fixed this?

Currently if I run `npm ci && npm run removeNPMAbsolutePaths` on a mac it tries to install `fsevents`.
```
> git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	node_modules/fsevents/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by aeisenberg** [comment]
I have no power at my house now and I'm running tethered to my phone, so I can't check this out myself on the codeql-action.

I _think_ I know what's happening. Locally, I never run `npm ci`. If I need to add or change dependencies, I just run `npm install -S foo && npm run removeNPMAbsolutePaths`. This seems to work for me. So, I never hit the problem above since I use a different workflow.

**Pull request merged**
